#!/bin/bash
# Writes SAVY-Secrets.xcconfig for Xcode from gateway env or Vercel.
# Run from repo root after gateway deploy.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
GATEWAY_ENV="$ROOT/gateway/.env.local"
OUT="$ROOT/SAVY-Secrets.xcconfig"
BASE_URL='https:/$()/savy-gateway.vercel.app/api/'
API_KEY=''

usage() {
  cat <<'EOF'
Usage: scripts/setup-savy-secrets.sh [--api-key KEY] [--pull-vercel]

Writes SAVY-Secrets.xcconfig (gitignored) so Xcode injects AWS_API_* into Info.plist.

Sources (first match wins):
  1. --api-key argument
  2. SAVY_API_KEY environment variable
  3. gateway/.env.local
  4. npx vercel env pull (with --pull-vercel, or when .env.local is missing)

Then rebuild SAVY in Xcode and run on your iPhone.
EOF
}

read_api_key_from_env_file() {
  local file="$1"
  [[ -f "$file" ]] || return 1
  local line
  line="$(grep -E '^SAVY_API_KEY=' "$file" | tail -n 1 || true)"
  [[ -n "$line" ]] || return 1
  API_KEY="${line#SAVY_API_KEY=}"
  API_KEY="${API_KEY%\"}"
  API_KEY="${API_KEY#\"}"
  [[ -n "$API_KEY" ]]
}

pull_vercel_env() {
  echo "Pulling production gateway env from Vercel…"
  (
    cd "$ROOT/gateway"
    npx vercel env pull .env.local --yes --environment=production
  )
}

validate_api_key() {
  local status
  status="$(
    curl -s -o /dev/null -w '%{http_code}' \
      -H "x-api-key: $API_KEY" \
      "https://savy-gateway.vercel.app/api/v1/entries?limit=1"
  )"
  case "$status" in
    200) echo "Gateway accepted the API key (HTTP 200)." ;;
    401) echo "Gateway rejected the API key (HTTP 401). Check SAVY_API_KEY on Vercel." >&2; return 1 ;;
    *) echo "Gateway returned HTTP $status — key may still be wrong." >&2; return 1 ;;
  esac
}

write_secrets_file() {
  cat >"$OUT" <<EOF
// Generated by scripts/setup-savy-secrets.sh — do not commit

AWS_API_BASE_URL = $BASE_URL
AWS_API_KEY = $API_KEY
EOF
  echo "Wrote $OUT"
}

PULL_VERCEL=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --api-key)
      API_KEY="${2:-}"
      shift 2
      ;;
    --pull-vercel)
      PULL_VERCEL=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ -z "$API_KEY" && -n "${SAVY_API_KEY:-}" ]]; then
  API_KEY="$SAVY_API_KEY"
fi

if [[ -z "$API_KEY" ]]; then
  read_api_key_from_env_file "$GATEWAY_ENV" || true
fi

if [[ -z "$API_KEY" && "$PULL_VERCEL" -eq 1 ]]; then
  pull_vercel_env
  read_api_key_from_env_file "$GATEWAY_ENV" || true
fi

if [[ -z "$API_KEY" && ! -f "$GATEWAY_ENV" ]]; then
  echo "No gateway/.env.local — trying Vercel env pull…"
  if pull_vercel_env; then
    read_api_key_from_env_file "$GATEWAY_ENV" || true
  fi
fi

if [[ -z "$API_KEY" ]]; then
  cat >&2 <<'EOF'
Could not find SAVY_API_KEY.

On your Mac (repo root):
  1. npx vercel login
  2. cd gateway && npx vercel link   # pick savy-gateway project
  3. cd .. && bash scripts/setup-savy-secrets.sh

Or paste the key from Vercel → Project → Settings → Environment Variables:
  bash scripts/setup-savy-secrets.sh --api-key 'your-key-here'
EOF
  exit 1
fi

write_secrets_file
validate_api_key
echo "Next: open SAVY.xcodeproj → Product → Clean Build Folder → run on your iPhone."
