#!/bin/bash
# Writes SAVY-Secrets.xcconfig from gateway/.env.local (gitignored). Run once after deploy.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/gateway/.env.local"
OUT="$ROOT/SAVY-Secrets.xcconfig"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "Missing $ENV_FILE — deploy gateway first."
  exit 1
fi

API_KEY=$(grep '^SAVY_API_KEY=' "$ENV_FILE" | cut -d= -f2-)

cat > "$OUT" <<EOF
// Generated by scripts/write-savy-secrets.sh — do not commit

AWS_API_BASE_URL = https:/$()/savy-gateway.vercel.app/api/
AWS_API_KEY = $API_KEY
EOF

echo "Wrote $OUT — rebuild SAVY in Xcode."
